language: bash
sudo: required
services:
    - docker
install:
    - docker build -t doconce/doconce .
script:
    - docker run doconce/doconce doconce --version
    # - docker run -v (pwd):/doconce doconce/doconce bash -c "apt-get install -yq iamerican ptex2tex python-pytest ipython-notebook && cd /doconce/test && py.test test_mintest.py"
